### ISSUE TITLE
Is there a way to schedule configmap or secret resource across target clusters?

### ISSUE THREAD

**Issue by lmxia** [admiraltyio/admiralty#101]
I found admiralty schedules workloads, like pod templates and i have no idea about other resources. 

what if my pod has a configmap? the configmap should be scheduled along with the delegate pod in the target cluster.

Is there a way, or admiralty is just designed only to handle workload?

**Comment by adrienjt** [comment]
The [intro](https://admiralty.io/docs/) says:

> Pod dependencies (config maps and secrets) and dependents (services and ingresses) "follow" delegate pods, i.e., they are copied as needed to target clusters.

It's meant to "just work". However, we could use more documentation on this feature, at least to make users more aware of it.

**Comment by lmxia** [comment]
Oh, i see..Thanks, a lot.
