### ISSUE TITLE
Outdated links in Argo blog tutorial

### ISSUE THREAD

**Issue by simonbonnefoy** [admiraltyio/admiralty#103]
Several links seem to be outdated in the [Argo tutorial](https://admiralty.io/blog/2019/01/17/running-argo-workflows-across-multiple-kubernetes-clusters), or the config seems not to be working. Here is how I replaced them in order to get everything to work.

Replace:
* [Argo installation](https://raw.githubusercontent.com/argoproj/argo/v2.2.1/manifests/install.yaml) by [Argo installation](https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/install.yaml)
 * [Admiralty service account](https://raw.githubusercontent.com/admiraltyio/multicluster-scheduler/master/config/samples/argo-workflows/_service-account.yaml) by [Admiralty service account](https://raw.githubusercontent.com/admiraltyio/admiralty/master/examples/argo-workflows/_service-account.yaml)
 * [Admiralty examples argo folder](https://raw.githubusercontent.com/admiraltyio/multicluster-scheduler/master/config/samples/argo-workflows/blog-scenario-a-singlecluster.yaml) by [Admiralty example argo folder](https://raw.githubusercontent.com/admiraltyio/admiralty/master/examples/argo-workflows/blog-scenario-a-singlecluster.yaml) for all the examples.

**Comment by adrienjt** [comment]
fixed
