### ISSUE TITLE
Question: What is the stable k8s version where I can install and test admiralty between 2 clusters?

### ISSUE THREAD

**Issue by dabenson4** [admiraltyio/admiralty#146]
I've started using admiralty on 1.17 and it worked until a few weeks back when we upgraded the cluster to 1.21 and now I get tons off issues and it is not working anymore, I've seen other threads and issue related to this https://github.com/admiraltyio/admiralty/issues/120, so wondering now, what is the right version so I can test this out, since 1.22 is not available on our EKS clusters yet.

**Comment by adrienjt** [comment]
[v0.15.0](https://github.com/admiraltyio/admiralty/releases/tag/v0.15.0) works with Kubernetes 1.21+

**Comment by adrienjt** [comment]
What issues are you getting? Actually, logs/exec still doesn't work: https://github.com/admiraltyio/admiralty/issues/133#issuecomment-1092196813

Anything else?

**Comment by adrienjt** [comment]
v0.16 works with k8s 1.24+.
