### ISSUE TITLE
Admiralty virtual node uses deprecated label for load balancer exclusion

### ISSUE THREAD

**Issue by bcarlock-emerge** [admiraltyio/admiralty#156]
Virtual nodes are currently using `alpha.service-controller.kubernetes.io/exclude-balancer` which was [deprecated](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md) in Kubernetes 1.16
The virtual node should use `node.kubernetes.io/exclude-from-external-load-balancers` or at least have this label as well.

**Comment by bcarlock-emerge** [comment]
I submitted a PR with the current label added in addition to the legacy label. https://github.com/admiraltyio/admiralty/pull/157

**Comment by adrienjt** [comment]
Fixed by #157. Thank you for your contribution!
