### ISSUE TITLE
Two podchaperons created

### ISSUE THREAD

**Issue by dimm0** [admiraltyio/admiralty#93]
Two podchaperons created if 2 namespaces of the same cluster target 2 namespaces of another cluster and have targets defined accordingly

**Comment by adrienjt** [comment]
I don't understand. Is this a bug report or a feature request? Could you be more specific and/or provide an example?

**Comment by dimm0** [comment]
Bug report. I'm getting 2 podchaperons created remotely for one proxy pod, which produces an error in proxy pod
Was trying for a while to find what's causing it and got nowhere...

**Comment by adrienjt** [comment]
Is "2 namespaces of the same cluster target 2 namespaces of another cluster and have targets defined accordingly" sufficient to consistently reproduce the bug?

**Comment by adrienjt** [comment]
Can't repro this issue. Is it still happening? Intermittently?

**Comment by dimm0** [comment]
LEt's close this

**Comment by dimm0** [comment]
Seeing this again when tried federating 2 namespaces, in the most recent version

**Comment by adrienjt** [comment]
Could be related to #119.

1) Are they both running?
2) How is RBAC configured? Are the targets configured using the same remote service account? Or a service account that can create pods in both namespaces?

Repro steps would be helpful.

**Comment by dimm0** [comment]
Pods aren't running, scheduler is complaining that there are 2 targets and is failing

Targets are using different SA in different namespaces

Could you try 2 clusters, and federate namespace A->A and B->B? And check it works as it should? That's basically all I need to do

**Comment by dimm0** [comment]
Yes!! That was it!
One service account in the target cluster had too much access :)
